version: '3.5'

services:
  nodebb:
    build: .
    restart: always
    ports:
      - '127.0.0.1:${PORT_FRONTEND}:${PORT_FRONTEND}'
    networks:
      - blogdb

networks:
  blogdb:
    external: true
