version: '3.5'

services:
  nodebb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:${PORT}:${PORT}'
    networks:
      - blogdb
    environment:
      URL: $URL
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      SECRET: $SECRET
      ADMIN_NAME: $ADMIN_NAME
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      PORT: $PORT
      BINARY_GRAPHQL_API: $BINARY_GRAPHQL_API
      BINARY_LOGIN_PAGE: $BINARY_LOGIN_PAGE
    volumes:
      - '${DATA_PATH}:/data'

networks:
  blogdb:
    external: true
