# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment CI

on: [ push, pull_request ]

jobs:

  # DEPLOY FORUM (DEVELOP)
  deploy-blog-dev:

    needs: [ deploy-dashboard-dev ]
    if: github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env variables file
        run: ./create_env_file.sh
        env:
          NODE_ENV: development
          PORT: 4687
          DATA_PATH: DEV__DATA_PATH
          URL: https://devforum.binary-coffee.dev
          DB_USER: ""
          DB_PASSWORD: ""
          DB_HOST: DEV__DB_HOST
          DB_PORT: DEV__DB_PORT
          DB_NAME: DEV__DB_NAME
          SECRET: DEV__SECRET
          ADMIN_NAME: DEV__ADMIN_NAME
          ADMIN_EMAIL: DEV__ADMIN_EMAIL
          ADMIN_PASSWORD: DEV__ADMIN_PASSWORD
          BINARY_GRAPHQL_API: https://api-dev.binary-coffee.dev/graphql
          BINARY_LOGIN_PAGE: https://dev.binary-coffee.dev/dashboard/login

      - name: Copy project to the hosting
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.DEV__REMOTE_TARGET }}

      - name: Deploy project with docker in hosting
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.DEV__REMOTE_TARGET }} && ./docker/deploy.sh dev_nodebb
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY}}

  # DEPLOY FORUM (PRODUCTION)
  deploy-blog-prod:

    needs: [ deploy-dashboard-prod ]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy project to the hosting
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.PROD__REMOTE_TARGET }}

      - name: Deploy project with docker in hosting
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.PROD__REMOTE_TARGET }} && PORT_FRONTEND=${{ secrets.PROD__PORT_FRONTEND_BLOG }} ./docker/deploy.sh blog-frontend-prod docker/docker-compose.yml
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY}}
